Compatibility for Windows Dev Environments
BYU-CS-Discord/CSBot pull request #35
Opened 2022-10-01 18:45 UTC by JstnMcBrd

(Will resolve Issue #34)

On Windows, Prettier was throwing errors because it expected Unix-style line endings. Now VS Code and Prettier should accept the default line endings of whatever operating system the project is on.

On Windows, `npm` scripts would fail because the Windows terminal did not accept Linux commands or file directories. Now VS Code should default to using Git Bash for the terminal, and a note was added to the README for Windows users to set `npm`'s default script shell to Git Bash.

And on a side note, I also added a setting to tell VS Code to auto-format files on save.

2022-10-01 18:51 UTC, AverageHelper requested changes

2022-10-01 18:51 UTC, AverageHelper commented on README.md
> +If you're on Windows, `npm` scripts will not working unless you tell `npm` to use Git Bash as its default shell when running commands.
Minor grammar nit:

```suggestion
If you're on Windows, `npm` scripts will not work unless you tell `npm` to use Git Bash as its default shell when running commands.
```

2022-10-01 18:51 UTC, AverageHelper commented on README.md
> +npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"
Added `$` for consistency

```suggestion
$ npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"
```

2022-10-01 18:55 UTC, AverageHelper commented
Making a note here in case I forget: Git's default config follows [the official guidance](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) for line endings on both Unix and Windows platforms:
- On Unix, the default value of `core.autocrlf` is `input`.
- On Windows, the default value of `core.autocrlf` is `true`.

This arrangement, plus the loosening of Prettier's `endOfLine` rule to `auto`, should mean that line endings "just work" regardless of the development platform, while maintaining Unix line endings in the remote.

2022-10-01 18:57 UTC, AverageHelper approved these changes

2022-10-02 02:15 UTC, gmacgre approved these changes
Honestly, seeing this solved will be really nice for me, since I've been manually entering the commands myself. LGTM

2022-10-02 02:35 UTC, merged