71-RoomFinder
BYU-CS-Discord/CSBot pull request #73
Opened 2023-02-04 23:58 UTC by ZYancey

Finish findRoom functionality

2023-02-05 06:24 UTC, AverageHelper requested changes

2023-02-05 06:24 UTC, AverageHelper commented on README.md
> +Searches for open rooms on BYU Campus. *'Now'* *'At'* and *'Between'* allow you to filter your search by time. *'When'* allows you to see when a specified room is available.
```suggestion
Searches for open rooms on BYU Campus. *'Now'*, *'At'*, and *'Between'* allow you to filter your search by time. *'When'* allows you to see when a specified room is available.
```

2023-02-05 06:24 UTC, AverageHelper commented on src/commands/findRoom.ts
> +function convertTo12Hour(time: string): string {
I think this function (and perhaps its neighbors) deserves a unit test or two

2023-02-05 06:24 UTC, AverageHelper commented on src/commands/findRoom.ts
> +						{ name: 'ANY', value: 'ANY' },
Might be wise to break this list of buildings into a string array, then construct these `name`/`value` object arrays in the four places they're needed

2023-02-05 06:24 UTC, AverageHelper commented on src/commands/findRoom.ts
> +						{ name: '8:00 AM', value: '08:00:00' },
Might be wise to break this list of times into an array, then re-use that array in the places it's needed

2023-02-27 16:38 UTC, AverageHelper commented on README.md
> +Searches for open rooms on BYU Campus. *'Now'*, *'At'*, and *'Between'* allow you to filter your search by time. *'When'* allows you to see when a specified room is available.
Fixing spacing as per Prettier suggestion:

```suggestion
### /findroom ( now / at / between / when )

Searches for open rooms on BYU Campus. *'Now'*, *'At'*, and *'Between'* allow you to filter your search by time. *'When'* allows you to see when a specified room is available.

```

2023-02-27 18:08 UTC, AverageHelper submitted a review, later dismissed

2023-02-27 18:08 UTC, AverageHelper commented
The red arrows in the coverage report make me sad, lol

2023-03-01 20:05 UTC, Plyb commented on src/commands/findRoom.ts
> +	try {
seems like we could collapse some of this by making a function that does all of this error handling

2023-03-01 20:07 UTC, Plyb commented on src/commands/findRoom.ts
> +				const requestedComic = await _getRoomsNow('now', input_bldg);
`comic` probably left over from the xkcd command

2023-03-01 20:08 UTC, Plyb commented on src/commands/findRoom.ts
> +	search_type: string,
It seems to me like `search_type` should probably just be a const inside this function (ditto for the other `getRooms` functions)

2023-03-09 00:21 UTC, AverageHelper approved these changes

2023-03-09 00:38 UTC, Plyb approved these changes

2023-03-09 00:38 UTC, merged