17 scoreboard
BYU-CS-Discord/CSBot pull request #90
Opened 2023-04-06 17:10 UTC by Plyb

Adds the `/stats` command and resolves #17

2023-04-06 18:10 UTC, AverageHelper requested changes

2023-04-06 18:10 UTC, AverageHelper commented on src/commands/stats.ts
> +	}
Same here:

```suggestion
	const statName = sanitize(interaction.options.getString(StatNameOption, true));
	const amount = interaction.options.getNumber(AmountOption, true);
```

2023-04-06 18:10 UTC, AverageHelper commented on src/commands/stats.ts
> +	}
Same here:

```suggestion
	const statName = sanitize(interaction.options.getString(StatNameOption, true));
```

2023-04-06 18:10 UTC, AverageHelper commented on src/commands/stats.ts
> +	}
Same here:

```suggestion
	const statName = sanitize(interaction.options.getString(StatNameOption, true));
```

2023-04-06 18:10 UTC, AverageHelper commented on src/commands/stats.ts
> +function mustIncludeNameError(): UserMessageError {
With the above suggestions, this function is unused, and may be removed.

2023-04-11 15:19 UTC, ZYancey approved these changes

2023-04-11 22:17 UTC, AverageHelper approved these changes
LGTM! What's the plan for migrating from Ze Kaiser's scoreboard?

2023-04-11 22:36 UTC, Plyb commented
I've got a copy of Ze Kaiser's scoreboard in JSON format from Arken. I'll use a script to port it over

2023-04-11 22:36 UTC, merged